name: Reminder bot 

on:
    schedule:
        - cron: "0 9 1,15 * *" # Run on the 1st and 15th of every month at 9am UTC
    workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  standup-reminder:
    name: Core dev standup reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Send message
        run: >
            uvx --from zulip zulip-send 
            --api-key "${{ secrets.REMINDER_BOT_API_KEY }}" 
            --user "${{ secrets.REMINDER_BOT_EMAIL }}"
            --site scverse.zulipchat.com
            --stream repo-management
            --subject "Core dev activity summary"
            --message "Dear @*core-devs*,\n\nplease provide some bullet points what you have been up to the last two weeks."
            --verbose

# TODO: this action has been pulled from github for a ToS violation
#   keepalive-job:
#     name: Keepalive Workflow
#     runs-on: ubuntu-latest
#     permissions:
#       actions: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: gautamkrishnar/keepalive-workflow@v2